### PR TITLE
Add missing imports

### PR DESCRIPTION
**Pull request by TristanCacqueray**
This change fixes the following errors with ghc-9.6:

  lib/Language/Souffle/Interpreted.hs:305:9: error: [GHC-88464]
      Variable not in scope:
        forM_

  lib/Language/Souffle/Compiled.hs:214:3: error: [GHC-88464]
      Variable not in scope:
        when :: Bool -> CMarshalSlow () -> CMarshalSlow ()
      |
  214 |   when (byteCount + offset > totalByteCount) $ do

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
You are welcome! That's it, I was fixing the ghc-wpc build with ghc-9.6, I plan on giving the ext-stg-interpreter a try to observe [simple-dsp](https://github.com/TristanCacqueray/simple-dsp).
