### ISSUE TITLE
Cannot compile on OSX with souffle 2.0.2

### ISSUE THREAD

**Issue by DavideFauri** [luc-tielen/souffle-haskell#32]
Hello,

I've tried to compile both this repository as it is, and the small "path" example in the README.
I'm on Catalina 10.15.5, souffle 2.0.2 was installed via `brew`, and my package.yaml already includes the `-std=c++17` and `-D__EMBEDDED_SOUFFLE__` flags.

These are the errors I'm getting on both attempts:

```
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell//private/var/folders/fj/4p0j7ts52h1f3gqr61m80plr0000gn/T/souffle-haskell-882bac48a192a11f/compiledprogram.cpp:316:19: error:
     error: non-virtual member function marked 'override' hides virtual member function
    |       
316 | void dumpInputs() override {
    |                   ^
void dumpInputs() override {
                  ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell/cbits/souffle/SouffleInterface.h:755:18: error:
     note: hidden overloaded virtual function 'souffle::SouffleProgram::dumpInputs' declared here: different number of parameters (1 vs 0)
        virtual void dumpInputs(std::ostream& out = std::cout) = 0;
                     ^
    |       
755 |     virtual void dumpInputs(std::ostream& out = std::cout) = 0;
    |                  ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell//private/var/folders/fj/4p0j7ts52h1f3gqr61m80plr0000gn/T/souffle-haskell-882bac48a192a11f/compiledprogram.cpp:325:20: error:
     error: non-virtual member function marked 'override' hides virtual member function
    |       
325 | void dumpOutputs() override {
    |                    ^
void dumpOutputs() override {
                   ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell/cbits/souffle/SouffleInterface.h:760:18: error:
     note: hidden overloaded virtual function 'souffle::SouffleProgram::dumpOutputs' declared here: different number of parameters (1 vs 0)
        virtual void dumpOutputs(std::ostream& out = std::cout) = 0;
                     ^
    |       
760 |     virtual void dumpOutputs(std::ostream& out = std::cout) = 0;
    |                  ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell//private/var/folders/fj/4p0j7ts52h1f3gqr61m80plr0000gn/T/souffle-haskell-882bac48a192a11f/compiledprogram.cpp:437:58: error:
     error: allocating an object of abstract class type 'souffle::Sf_compiledprogram'
    |       
437 | SouffleProgram *newInstance_compiledprogram(){return new Sf_compiledprogram;}
    |                                                          ^
SouffleProgram *newInstance_compiledprogram(){return new Sf_compiledprogram;}
                                                         ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell/cbits/souffle/SouffleInterface.h:755:18: error:
     note: unimplemented pure virtual method 'dumpInputs' in 'Sf_compiledprogram'
        virtual void dumpInputs(std::ostream& out = std::cout) = 0;
                     ^
    |       
755 |     virtual void dumpInputs(std::ostream& out = std::cout) = 0;
    |                  ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell/cbits/souffle/SouffleInterface.h:760:18: error:
     note: unimplemented pure virtual method 'dumpOutputs' in 'Sf_compiledprogram'
        virtual void dumpOutputs(std::ostream& out = std::cout) = 0;
                     ^
    |       
760 |     virtual void dumpOutputs(std::ostream& out = std::cout) = 0;
    |                  ^
            
/Users/me/Documents/Workspace/Git/Projects/souffle-haskell//private/var/folders/fj/4p0j7ts52h1f3gqr61m80plr0000gn/T/souffle-haskell-882bac48a192a11f/compiledprogram.cpp:443:12: error:
     error: allocating an object of abstract class type 'souffle::Sf_compiledprogram'
    |       
443 | return new Sf_compiledprogram();
    |            ^
return new Sf_compiledprogram();
           ^
4 errors generated.
`gcc' failed in phase `C Compiler'. (Exit code: 1)
            
--  While building package souffle-haskell-2.0.1 using:
      /Users/me/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build lib:souffle-haskell exe:import-souffle-headers test:souffle-haskell-test --ghc-options " -fdiagnostics-color=always"
```

**Comment by luc-tielen** [comment]
Hi, thank you for reporting this issue!

This is a compile error from the C++ code that Soufflé generates. I will create a ticket there to notify them of this.
I think a `virtual` keyword needs to be added to the generated output.

I haven't tested this repository yet with Soufflé 2.0.2, right now latest version I tested it with is 2.0.1. You can try downgrading to that for now. It's on my planning in the near future to upgrade to the latest version though.

**Comment by DavideFauri** [comment]
Wow, thanks for the quick response!

I've successfully downgraded to souffle 2.0.1: before describing the results, I should probably write down what I did, for posterity.

#### How I downgraded souffle (or any brew package)

```bash
git clone https://github.com/souffle-lang/homebrew-souffle # brew recipe for souffle
cd homebrew-souffle
git checkout fbd35046 # commit with v2.0.1 tag
brew unlink souffle # I already had souffle 2.0.2 installed, so I needed to unlink it before installing another version
brew install Formula/souffle.rb
brew pin souffle # tell brew not to overwrite souffle 2.0.1 when updating
```

Now I can switch between different versions of souffle with `brew switch souffle [VERSION]`.

#### Results

I can compile the `souffle-haskell` library, and run the tests. I fail 21 cases out of 93, all of them related to interpreted souffle; compiled souffle works fine. Apparently it doesn't seem to find the souffle interpreter, which is weird, because `locateSouffle` calls the shell command `which souffle`, and that works on my terminal. Is there a way to verify that `locateSouffle` successfully executes the command?

I also managed to compile the example, but only after looking at your `package.yaml` and including this option in mine:

```yaml
 when:
    - condition: os(darwin)
      extra-libraries: c++
```

**Comment by luc-tielen** [comment]
Thanks for being thorough with how you downgrade to souffle 2.0.1.

How are you compiling the library? Just via cabal? I have to admit that I never tried running tests on OSX without being in a nix-shell.. 😅 

I noticed the line numbers in the README now point to the wrong lines since I added automatic import script. Fixing this would have avoided your confusion about OS-specific C++ flags.

If you can compile the example that means you have the C++ / Haskell compile flags now properly set up, but maybe still some issues with location of interpreter executable (compiled mode doesn't need the `souffle` executable).
You can try specifying `SOUFFLE_BIN=/path/to/souffle make tests` and see if that helps?
(And if that doesn't work: `SOUFFLE_BIN=/path/to/souffle DATALOG_DIR=tests/fixtures/ cabal run souffle-haskell-test`)

**Comment by luc-tielen** [comment]
An update: I tried upgrading to souffle 2.0.2 but this also requires me to copy over all relevant C++ headers for souffle.
I have an automated script for this but it broke (probably due to new location of header files in souffle repo).
I will make my script more robust against changes like this, but this will involve quite some refactoring, might take some time.
For now you can continue using 2.0.1 though.

**Comment by luc-tielen** [comment]
@DavideFauri can you check if #33 fixes your issue? For me I can run the test suite without errors now (though I seem to get a C++ warning about mixing `&&` with `||` without parentheses (that should be fixed in souffle repo).

**Comment by luc-tielen** [comment]
I haven't had the chance to finish this in the last few weeks, but just spend some time setting up another repo so I can test this more easily myself: https://github.com/luc-tielen/souffle-haskell-example 
I did some more commits in #33 and this seems to fix it!
